[package]
name = "umbra-core"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tracing.workspace = true
