[package]
name = "umbra-storage-nfs"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
umbra-core = { path = "../umbra-core" }
umbra-storage = { path = "../umbra-storage" }
libc = "=0.2.189"
uuid.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
