[package]
name = "umbra-storage-local"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
umbra-core = { path = "../umbra-core" }
umbra-storage = { path = "../umbra-storage" }
rustix = { version = "=1.1.5", features = ["process"] }
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
